name: Publish new version to pesde registry

on:
  workflow_dispatch:

jobs:
  build:
    name: Build project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.7

      - name: Set up pesde
        uses: axiom-co/setup-pesde@v0.4.1
        with:
          version: v0.7.0-rc.4+registry.0.2.3-rc.2

      - name: Install packages
        run: |
          pesde install