name: Publish new version to pesde registry

on:
  workflow_dispatch:
  release:
    types: [released, prereleased]

concurrency:
  group: ${{ github.workflow }}

jobs:
  build:
    name: Build project
    runs-on: ubuntu-22.04
    environment: Production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.7

      - name: Set up pesde
        uses: axiom-co/setup-pesde@v0.4.1
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          token: ${{ secrets.PESDE_TOKEN }}

      - name: Install dependencies
        run: |
          pesde install