name: Publish new version to pesde registry

on:
  workflow_dispatch:
  release:
    types: [released, prereleased]

concurrency:
  group: ${{ github.workflow }}

jobs:
  build:
    name: Build project
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.7

      - name: Set up pesde
        uses: axiom-co/setup-pesde@v0.4.1
        with:
          version: v0.7.0-rc.4+registry.0.2.3-rc.2
          token: ${{ secrets.PESDE_TOKEN }}

      - name: Publish to pesde registry
        run: |
          pesde publish
          y